# Minimal Makefile for Sphinx documentation
SPHINXBUILD   = python -m sphinx
SOURCEDIR     = source
BUILDDIR      = build

html:
	$(SPHINXBUILD) -M html $(SOURCEDIR) $(BUILDDIR)

clean:
	$(SPHINXBUILD) -M clean $(SOURCEDIR) $(BUILDDIR)
